# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "cucumber", "~> 9.2.0"
gem "cucumber-compatibility-kit", "~> 9.0"
gem "json"
gem "rspec"
